<%@ Page Title="分类管理" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="CategoryMaster.aspx.cs" Inherits="Admin_CategoryMaster" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
  <a href="CategoryMaster.aspx">分类管理</a>
  <br />
  <br />
  <a href="PressMaster.aspx">出版社管理</a>
  <br />
  <br />
  <a href="BookMaster.aspx">图书管理</a>
  <br />
  <br />
  <a href="OrderMaster.aspx">订单管理</a>
  <br />
  <br />
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="Server">
  <asp:LinqDataSource ID="LinqDataSource1"
    runat="server" ContextTypeName="MyBookShopDataContext" TableName="Category" AutoPage="true" EnableUpdate="true" EnableInsert="true" EnableDelete="true">
  </asp:LinqDataSource>
  <asp:DetailsView ID="DetailsView1" runat="server" DataSourceID="LinqDataSource1" DataKeyNames="CategoryId" AutoGenerateRows="false" AutoGenerateEditButton="true" AutoGenerateInsertButton="true" AutoGenerateDeleteButton="true"
    AllowPaging="true"  OnItemDeleting="DetailsView1_ItemDeleting">
    <Fields>
      <asp:BoundField HeaderText="分类ID" DataField="CategoryId" Visible="false" />
      <asp:BoundField HeaderText="分类名称" DataField="Name" />
      <asp:BoundField HeaderText="分类描述" DataField="Descn" />
    </Fields>
  </asp:DetailsView>
  <asp:Label ID="lblError" runat="server" ForeColor="Red"></asp:Label>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder3" runat="Server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="ContentPlaceHolder4" runat="Server">
</asp:Content>
