<%@ Page Title="供应商管理" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="PressMaster.aspx.cs" Inherits="Admin_PressMaster" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
  <a href="CategoryMaster.aspx">分类管理</a>
  <br />
  <br />
  <a href="PressMaster.aspx">出版社管理</a>
  <br />
  <br />
  <a href="BookMaster.aspx">图书管理</a>
  <br />
  <br />
  <a href="OrderMaster.aspx">订单管理</a>
  <br />
  <br />
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="Server">
  <asp:LinqDataSource ID="LinqDataSource1" runat="server" ContextTypeName="MyBookShopDataContext" TableName="Press" AutoPage="true" EnableUpdate="true" EnableInsert="true" EnableDelete="true">
  </asp:LinqDataSource>
  <asp:DetailsView DataSourceID="LinqDataSource1" DataKeyNames="PressId" AutoGenerateRows="false" AutoGenerateEditButton="true" AutoGenerateInsertButton="true" AutoGenerateDeleteButton="true"
    AllowPaging="true" ID="DetailsView1" OnItemDeleting="DetailsView1_ItemDeleting"
    runat="server">
    <Fields>
      <asp:BoundField HeaderText="出版社ID" DataField="PressId" Visible="false" />
      <asp:BoundField HeaderText="出版社名称" DataField="Name" />
      <asp:BoundField HeaderText="地址" DataField="Addr" />
      <asp:BoundField HeaderText="邮编" DataField="Zip" />
      <asp:BoundField HeaderText="电话" DataField="Phone" />
    </Fields>
  </asp:DetailsView>
  <asp:Label ID="lblError" runat="server" ForeColor="Red"></asp:Label>

</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder3" runat="Server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="ContentPlaceHolder4" runat="Server">
</asp:Content>


